name: 'Go: test & lint'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up Cache Environment
      run: mkdir -p ~/go/pkg/mod

    - name: gofmt
      shell: bash
      run: files=$(gofmt -l .) && echo "${files:-[OK] All files are formatted}" && test -z "$files"

    - name: Create dummy .min files
      run: touch assets/index.min.html assets/main.min.js

    - name: staticcheck
      uses: dominikh/staticcheck-action@v1.1.0
      with:
        version: "2021.1.2"

    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./...
      env:
        GAKUJO_USERNAME: ${{ secrets.GAKUJO_USERNAME }}
        GAKUJO_PASSWORD: ${{ secrets.GAKUJO_PASSWORD }}
        EDSTEM_EMAIL:    ${{ secrets.EDSTEM_EMAIL }}
        EDSTEM_PASSWORD: ${{ secrets.EDSTEM_PASSWORD }}
        TEAMS_EMAIL:     ${{ secrets.TEAMS_EMAIL }}
        TEAMS_PASSWORD:  ${{ secrets.TEAMS_PASSWORD }}
        NOW_ON_CI: "1"
